### ISSUE TITLE
Make scripts portable

### ISSUE THREAD

**Issue by ghomasHudson** [Visual-modelling/cnn_visual_modelling#2]
@Jumperkables Looking at your `scripts` dir, it needs a few changes to be portable and useable for anyone else (or even if you move the folder):

`repo_rootdir` doesn't need to be specified by the user as you can work it out within `main.py`:
```python
import os
import sys

repo_rootdir =  os.path.dirname(os.path.realpath(sys.argv[0]))
```

Removing all the absolute paths is also needed for anyone else to use them. A standard approach would be to store everything in folders under the main repo (e.g. /results /data etc...). If you really need them to be stored elsewhere you can use [symlinks](https://www.howtogeek.com/287014/how-to-create-and-use-symbolic-links-aka-symlinks-on-linux/): `ln -s /path/to/real/storage/location /path/to/repo/data` to create shortcuts to the data elsewhere without putting all this logic inside your python scripts.

**Comment by Jumperkables** [comment]
Done it, and giving example scripts now. Cheers Hudson
